# Generated by Django 4.2 on 2023-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='скидка'),
        ),
    ]
